import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Daniel Work in progress",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header 
         style={{backgroundColor: "grey", color: "white", padding: "1rem"}}
        >
          <p>Header</p>
        </header>
        <main>{children}</main>
        <footer 
          style={{backgroundColor: "blue", color: "white", padding: "1rem"}}
        >
          <p>Footer</p>
          <Footer/>
        </footer> 
      </body>
    </html>
  );
}
